//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2BDetail
    {
        public long Id { get; set; }
        public long StockId { get; set; }
        public long PackageId { get; set; }
        public long OrderID { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal PackageQuantity { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual Order Order { get; set; }
        public virtual Package Package { get; set; }
    }
}
