//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomShirtsOrder
    {
        public long Id { get; set; }
        public int Type { get; set; }
        public decimal ShirtPrice { get; set; }
        public Nullable<decimal> FrontPrice { get; set; }
        public Nullable<decimal> BackPrice { get; set; }
        public string ShirtColor { get; set; }
        public string BackImageUrl { get; set; }
        public string FrontImageUrl { get; set; }
        public long OrderId { get; set; }
        public Nullable<int> Size { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifieBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
