//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomShirt
    {
        public long Id { get; set; }
        public int Type { get; set; }
        public decimal ShirtPrice { get; set; }
        public decimal FrontPrintPrice { get; set; }
        public decimal BackPrintPrice { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> Size { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
